
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://${Projecthost:localhost}:5432/PartTimeDB
    username: ${Projectuser:postgres}
    password: ${Projectpw:test123}

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    open-in-view: false
    generate-ddl: true
  data:
    jpa:
      repositories.enabled: true

service:
    frontend:
      url: ${UI_APPLICATIONS:http://localhost:4200}
